### ISSUE TITLE
Resource grid layout on mobile

### ISSUE THREAD

**Issue by parthsarin** [parthsarin/stanford-craft#14]
<img width="612" alt="" src="https://user-images.githubusercontent.com/5355724/235336820-7ba0baf3-5b50-41f1-acb6-9861a8161f71.png">

The layout on mobile for the resource grid — as seen in the image above — doesn't position the search and filter panel in the correct location.

**Comment by ddeepak95** [comment]
hi @parthsarin, I have created a [pr](https://github.com/parthsarin/stanford-craft/pull/20) for this bug fix. Please check and let me know if it works!
