### ISSUE TITLE
Scrolling doesn't update on the resources page

### ISSUE THREAD

**Issue by parthsarin** [parthsarin/stanford-craft#15]
On most pages (e.g., the credits page), as you scroll down the page, the navbar on the left sticks to the side of the screen. But on the new resources page, if you scroll down, the navbar gets stuck and doesn't scroll with the page.

<img width="1728" alt="the navbar is farther up the page while the user has scrolled" src="https://user-images.githubusercontent.com/5355724/235415508-5ec250bb-e00a-492f-b2d4-c6ccb85505c3.png">

Steps to reproduce (Google Chrome v112, Mac OSX, Macbook Pro):
1. Open https://craft.stanford.edu/dash/resources
2. Start at the top of the page 
3. Scroll down the page, without stopping (i.e., don't release the scroll wheel or allow the page to scroll continuously)

**Comment by Isabel-S** [comment]
I haven't been able to replicate this issue... is it still there?

**Comment by parthsarin** [comment]
Yeah, it’s still there on my computer. I can show you at our meeting today, maybe!

**Comment by Isabel-S** [comment]
Haven't been able to figure this out, but I have a feeling that once I work on the sticky for the search it will go away

**Comment by Isabel-S** [comment]
c
